# .github/workflows/code_checks.yaml
name: Code_Checks

on: ["pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            stability: prefer-stable

    name: PHP ${{ matrix.php }} tests - ${{ matrix.stability }}
    steps:
      # basically git clone
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov, dom, mbstring, pcntl
          coverage: pcov

      - name: Install dependencies
        #run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction
        # To install laminas/code Version 4.5.x with php 8.1 support
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --with-all-dependencies

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
